name: aureus
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Exo
      fonts:
        - asset: /Users/amandasouthworth/Desktop/Aureus/Assets/Fonts/Exo-Light.ttf
        - asset: /Users/amandasouthworth/Desktop/Aureus/Assets/Fonts/Exo-Regular.ttf
        - asset: /Users/amandasouthworth/Desktop/Aureus/Assets/Fonts/Exo-Medium.ttf
