name: aureus
description: A design system for ethical tech use cases involving sensitive populations / functionality
version: 0.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_secure_storage: ^4.2.1

flutter:
  assets:
    - lib/assets/Dark Blur - Landscape.png
    - lib/assets/Dark Blur - Portrait.png
    - lib/assets/Dark Fluid - Landscape.png
    - lib/assets/Dark Fluid - Portrait.png
    - lib/assets/Icon - Dark Mode.png
    - lib/assets/Icon - Light Mode.png
    - lib/assets/Light Blur - Landscape.png
    - lib/assets/Light Blur - Portrait.png
    - lib/assets/Light Fluid - Landscape.png
    - lib/assets/Light Fluid - Portrait.png

  fonts:
    - family: Aureus
      fonts:
        - asset: lib/fonts/Aureus.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
